// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbyqfvbkvfxenydjqrgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieXFmdmJrdmZ4ZW55ZGpxcmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODIxNDksImV4cCI6MjA2NDE1ODE0OX0.qkduNLEgmB3etVJ4Z6PkGEuEjMgzN2Jnsdf7fxVy4nA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);